version: 2
jobs:
  build:
    working_directory: ~/livgrhm-v4
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/livgrhm-v4
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run ci
      - run: npm run build
      - persist_to_workspace:
           root: .
           paths: dist
  deploy:
    working_directory: ~/livgrhm-v4
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - attach_workspace:
          at: ~/livgrhm-v4
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync dist s3://$AWS_S3_BUCKET --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
